module 2 completed
Denis-Milashuk/epamJavaAdvancedCourse pull request #2
Opened 2023-10-23 17:36 UTC by Denis-Milashuk

2023-10-24 07:01 UTC, unix-follower requested changes

2023-10-24 07:01 UTC, unix-follower commented on module_2_task_1/grpc_client/src/main/java/com/epam/javaAdvanced/grpc/client/web/PingPongController.java
> +        return this.pingPongClient.sayPong(PingPongRequest.newBuilder().setMessage("Ping " + message).build()).getMessage();
Optional: create a service a delegate this call to it.

2023-10-24 07:01 UTC, unix-follower commented on module_2_task_1/README.md
> +```
Optional: append shell after backticks to get syntax highlighting -```shell

2023-10-24 07:01 UTC, unix-follower commented on module_2_task_2/README.md
> +docker compose -f ./module_2_task_2/docker/docker-compose.yml up
That is outdated approach to work with Compose plugin. And it might lead to [this](https://github.com/docker/compose/issues/8630) problem.

Optional: replace with dash
```shell
docker-compose -f ./module_2_task_2/docker/docker-compose.yml up
```

2023-10-24 07:01 UTC, unix-follower commented on module_2_task_2/src/main/java/com/epam/javaAdvanced/kafka/web/EmployeeController.java
> +        kafkaTemplate.send(topic, employee);
The send method works asynchronously. If you want that behavior then you have nothing to worry about. Otherwise, add join call on this CompletableFuture object.

2023-10-24 07:01 UTC, unix-follower commented on module_2_task_2/src/main/resources/employee-schema.avsc
There is a requirement: Include Avro schema version/id into the massage so a client can understand which schema to use.

If you leave it as is then you final grade will be decreased

2023-10-24 18:14 UTC, Denis-Milashuk commented on module_2_task_1/grpc_client/src/main/java/com/epam/javaAdvanced/grpc/client/web/PingPongController.java
> +        return this.pingPongClient.sayPong(PingPongRequest.newBuilder().setMessage("Ping " + message).build()).getMessage();
fixed

2023-10-24 18:19 UTC, Denis-Milashuk commented on module_2_task_1/README.md
> +```
fixed

2023-10-24 18:34 UTC, Denis-Milashuk commented on module_2_task_2/README.md
> +docker compose -f ./module_2_task_2/docker/docker-compose.yml up
fixed

2023-10-24 19:05 UTC, Denis-Milashuk commented on module_2_task_2/src/main/java/com/epam/javaAdvanced/kafka/web/EmployeeController.java
> +        kafkaTemplate.send(topic, employee);
fixed

2023-10-24 20:30 UTC, Denis-Milashuk commented on module_2_task_2/src/main/resources/employee-schema.avsc
fixed

2023-10-25 06:22 UTC, unix-follower approved these changes

2023-11-01 21:49 UTC, merged